#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1an-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1ao-u3-gnd.py \
  --route1an-drc-json /tmp/route1an.json \
  --route1an-pin-net-audit /tmp/route1an-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1ao.json \
  hardware/main-board/pcb/route-r13-1ao/AegisBioWatch-MainBoard-Route1ao-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1ao/AegisBioWatch-MainBoard-Route1ao-r13.kicad_pcb \
  --output /tmp/route1ao-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1ao.json'))
a=json.load(open('/tmp/route1ao-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1ao/routing-seed-r13-1ao.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1ao/AegisBioWatch-MainBoard-Route1ao-r13.kicad_pcb')
conn=r.get('connections',{}).get('U3.4/GND',{})

accepted_source_sha='e87da7f83af3609e5a7264215cbc26243b4dc8168fc34002ccdf01629825bc29'
accepted_pcb_sha='0854849492c272968117c1c96676ea94fac4671810b3f8a41c59ef5c8d6a4b9a'
accepted_artifact_digest='sha256:abac53552156c789f03dd4921961b0c1d045adf9f1a86933e4601eedc090df08'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1an_sha256':r.get('source_route1an_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1an_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'u3_value':conn.get('u3_value'),
  'u3_1_net':conn.get('u3_1_net'),
  'u3_2_net':conn.get('u3_2_net'),
  'u3_3_net':conn.get('u3_3_net'),
  'u3_4_net':'GND' if 'U3.4/GND' in r.get('connections',{}) else None,
  'u3_5_net':conn.get('u3_5_net'),
  'u3_6_net':conn.get('u3_6_net'),
  'u3_7_net':conn.get('u3_7_net'),
  'u3_8_net':conn.get('u3_8_net'),
  'u3_4_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1an_geometry_modified':r.get('accepted_route1an_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1an_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1ao-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=134:
    raise SystemExit('route1ao DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1ao audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1ao routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1ao placement scope gate failed')
expected={
  'u3_value':'W25Q256JWPIQ 256Mbit',
  'u3_1_net':'FLASH_CS_N',
  'u3_2_net':'AUX_SPI_MISO',
  'u3_3_net':'FLASH_WP_N',
  'u3_4_net':'GND',
  'u3_5_net':'AUX_SPI_MOSI',
  'u3_6_net':'AUX_SPI_SCK',
  'u3_7_net':'FLASH_HOLD_N',
  'u3_8_net':'+1V8',
}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1ao U3 identity/net gate failed: {key}={out[key]!r}')
if out['u3_4_pad_mm'] != [3.58,8.53] or out['gnd_via_mm'] != [2.8,8.53]:
    raise SystemExit('route1ao U3 geometry gate failed')
if out['accepted_route1an_geometry_modified'] is not False:
    raise SystemExit('route1ao accepted route1an geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1ao frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
# A pull_request run can regenerate different bytes as its synthesized merge
# base evolves; topology/geometry/DRC/audit/component-identity gates remain
# authoritative.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1ao note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
