#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1ax-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1ay-r303-gnd.py \
  --route1ax-drc-json /tmp/route1ax.json \
  --route1ax-pin-net-audit /tmp/route1ax-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1ay.json \
  hardware/main-board/pcb/route-r13-1ay/AegisBioWatch-MainBoard-Route1ay-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1ay/AegisBioWatch-MainBoard-Route1ay-r13.kicad_pcb \
  --output /tmp/route1ay-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1ay.json'))
a=json.load(open('/tmp/route1ay-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1ay/routing-seed-r13-1ay.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1ay/AegisBioWatch-MainBoard-Route1ay-r13.kicad_pcb')
conn=r.get('connections',{}).get('R303.2/GND',{})

accepted_source_sha='52ef9367b1f89ff8aa833f2dbc7528a9b053f14a410dbe6872c20fbf453394b6'
accepted_pcb_sha='1d1d358dffce04338743ccfa21c16929ceeeebd0643587a08e178ca296d01be7'
accepted_artifact_digest='sha256:92b46a1d2f4788f7509de85bd9fcd843db7eb83ecdba28423d93d9c998e75223'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1ax_sha256':r.get('source_route1ax_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1ax_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'r303_value':conn.get('r303_value'),
  'r303_1_net':conn.get('r303_1_net'),
  'r303_2_net':conn.get('r303_2_net'),
  'r303_1_pad_mm':conn.get('r303_1_pad_mm'),
  'r303_2_pad_mm':conn.get('r303_2_pad_mm'),
  'target_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1ax_geometry_modified':r.get('accepted_route1ax_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1ax_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1ay-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=124:
    raise SystemExit('route1ay DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1ay audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1ay routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1ay placement scope gate failed')
expected={'r303_value':'100k PD','r303_1_net':'HAPTIC_TRIG','r303_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1ay R303 identity/net gate failed: {key}={out[key]!r}')
if out['r303_1_pad_mm'] != [22.505,25.975] or out['r303_2_pad_mm'] != [23.145,25.975]:
    raise SystemExit('route1ay R303 geometry gate failed')
if out['target_pad_mm'] != [23.145,25.975] or out['gnd_via_mm'] != [23.145,26.63]:
    raise SystemExit('route1ay target geometry gate failed')
if out['accepted_route1ax_geometry_modified'] is not False:
    raise SystemExit('route1ay accepted route1ax geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1ay frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1ay note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
