#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1aw-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1ax-j101-upper-gnd.py \
  --route1aw-drc-json /tmp/route1aw.json \
  --route1aw-pin-net-audit /tmp/route1aw-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1ax.json \
  hardware/main-board/pcb/route-r13-1ax/AegisBioWatch-MainBoard-Route1ax-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1ax/AegisBioWatch-MainBoard-Route1ax-r13.kicad_pcb \
  --output /tmp/route1ax-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1ax.json'))
a=json.load(open('/tmp/route1ax-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1ax/routing-seed-r13-1ax.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1ax/AegisBioWatch-MainBoard-Route1ax-r13.kicad_pcb')
conn=r.get('connections',{}).get('J101.2/GND upper',{})

accepted_source_sha='26cbd2770ccf4553fa43a2e4199df658651a90d8a7e48bcdf6acc96c770e814a'
accepted_pcb_sha='c9c7792305a3d0a27092d78b2d109f0f668564b2d7052db64e51d7f9c7c410d6'
accepted_artifact_digest='sha256:d78e293b0a233c3ca9a9a70c98c630546083ba5855c96751ea5c253408fab7c8'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1aw_sha256':r.get('source_route1aw_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1aw_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'j101_value':conn.get('j101_value'),
  'j101_1_net':conn.get('j101_1_net'),
  'j101_2_net':conn.get('j101_2_net'),
  'j101_1_pads_mm':conn.get('j101_1_pads_mm'),
  'j101_2_pads_mm':conn.get('j101_2_pads_mm'),
  'target_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1aw_geometry_modified':r.get('accepted_route1aw_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1aw_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1ax-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=125:
    raise SystemExit('route1ax DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1ax audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1ax routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1ax placement scope gate failed')
expected={'j101_value':'EVQPLDA15_SHIP_WAKE','j101_1_net':'SHIP_HOLD','j101_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1ax J101 identity/net gate failed: {key}={out[key]!r}')
if out['j101_1_pads_mm'] != [[34.775,10.625],[34.775,15.025]]:
    raise SystemExit('route1ax J101.1 geometry gate failed')
if out['j101_2_pads_mm'] != [[38.475,10.625],[38.475,15.025]]:
    raise SystemExit('route1ax J101.2 geometry gate failed')
if out['target_pad_mm'] != [38.475,10.625] or out['gnd_via_mm'] != [39.2,10.625]:
    raise SystemExit('route1ax target geometry gate failed')
if out['accepted_route1aw_geometry_modified'] is not False:
    raise SystemExit('route1ax accepted route1aw geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1ax frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1ax note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
