#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1ba-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1bb-j9-left-gnd.py \
  --route1ba-drc-json /tmp/route1ba.json \
  --route1ba-pin-net-audit /tmp/route1ba-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1bb.json \
  hardware/main-board/pcb/route-r13-1bb/AegisBioWatch-MainBoard-Route1bb-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1bb/AegisBioWatch-MainBoard-Route1bb-r13.kicad_pcb \
  --output /tmp/route1bb-audit.json

python3 - <<'PY'
import hashlib, json
from pathlib import Path

d=json.load(open('/tmp/route1bb.json'))
a=json.load(open('/tmp/route1bb-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1bb/routing-seed-r13-1bb.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1bb/AegisBioWatch-MainBoard-Route1bb-r13.kicad_pcb')
c=r.get('connections',{}).get('J9.1/GND left pad',{})

accepted_pcb_sha='1673120b753fa498d4ca3cce7f7a2014088114ee26d58cfcb23cdc36643f8fa3'
accepted_artifact_digest='sha256:df2534c4cb89f9324857e56480dd109765de18be21cf13ab9d31c57a7bb377e0'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'j9_value':c.get('j9_value'),
  'j9_1_net':c.get('j9_1_net'),
  'j9_2_net':c.get('j9_2_net'),
  'j9_1_pad_positions_mm':c.get('j9_1_pad_positions_mm'),
  'j9_2_pad_positions_mm':c.get('j9_2_pad_positions_mm'),
  'target_pad_mm':c.get('pad_mm'),
  'gnd_via_mm':c.get('gnd_via_mm'),
  'target_physical_pad':c.get('target_physical_pad'),
  'right_j9_1_route1ba_status':r.get('right_j9_1_route1ba_status'),
  'j9_side_button_pads_status':r.get('j9_side_button_pads_status'),
  'accepted_route1ba_geometry_modified':r.get('accepted_route1ba_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(out['pcb_sha256']==accepted_pcb_sha)
print(json.dumps(out,indent=2))
Path('/tmp/route1bb-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=121:
    raise SystemExit('route1bb DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1bb audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1bb routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1bb placement scope gate failed')
if out['j9_value']!='EVQPUK02K_SIDE_BUTTON' or out['j9_1_net']!='GND' or out['j9_2_net']!='SIDE_BUTTON':
    raise SystemExit('route1bb J9 identity/net gate failed')
if out['j9_1_pad_positions_mm'] != [[20.85,5.775],[26.0,5.775]]:
    raise SystemExit('route1bb J9.1 duplicate-pad geometry gate failed')
if out['j9_2_pad_positions_mm'] != [[20.85,7.475],[26.0,7.475]]:
    raise SystemExit('route1bb J9.2 duplicate-pad geometry gate failed')
if out['target_pad_mm'] != [20.85,5.775] or out['gnd_via_mm'] != [19.85,5.775] or out['target_physical_pad']!='left J9.1/GND':
    raise SystemExit('route1bb target geometry gate failed')
if out['right_j9_1_route1ba_status']!='UNCHANGED' or out['j9_side_button_pads_status']!='UNCHANGED':
    raise SystemExit('route1bb J9 preserved-pad gate failed')
if out['accepted_route1ba_geometry_modified'] is not False:
    raise SystemExit('route1bb accepted route1ba geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1bb frozen-interface scope gate failed')

if not out['byte_identity_matches_accepted_artifact']:
    print('route1bb note: regenerated bytes differ from accepted Artifact provenance; electrical/geometry gates remain authoritative')
PY
