#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1ar-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1as-c4-gnd.py \
  --route1ar-drc-json /tmp/route1ar.json \
  --route1ar-pin-net-audit /tmp/route1ar-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1as.json \
  hardware/main-board/pcb/route-r13-1as/AegisBioWatch-MainBoard-Route1as-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1as/AegisBioWatch-MainBoard-Route1as-r13.kicad_pcb \
  --output /tmp/route1as-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1as.json'))
a=json.load(open('/tmp/route1as-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1as/routing-seed-r13-1as.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1as/AegisBioWatch-MainBoard-Route1as-r13.kicad_pcb')
conn=r.get('connections',{}).get('C4.2/GND',{})

accepted_source_sha='62aec7bb0bbe68653771bac810b7f929c6f0877e9cee646072c1c7236c59a5dd'
accepted_pcb_sha='3168e6df5549cf9a122bc008836a6a29e5be0ad4392bd51e12bb52fe6b750c3c'
accepted_artifact_digest='sha256:ca96ecc56f4c070d94a2e7dba3df7cf7ccae2cc03665f9b4891f7af8a99589bf'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1ar_sha256':r.get('source_route1ar_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1ar_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'c4_value':conn.get('c4_value'),
  'c4_1_net':conn.get('c4_1_net'),
  'c4_2_net':conn.get('c4_2_net'),
  'c4_2_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1ar_geometry_modified':r.get('accepted_route1ar_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1ar_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1as-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=130:
    raise SystemExit('route1as DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1as audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1as routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1as placement scope gate failed')
expected={'c4_value':'100nF','c4_1_net':'+1V8','c4_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1as C4 identity/net gate failed: {key}={out[key]!r}')
if out['c4_2_pad_mm'] != [41.645,14.975] or out['gnd_via_mm'] != [42.25,14.975]:
    raise SystemExit('route1as C4 geometry gate failed')
if out['accepted_route1ar_geometry_modified'] is not False:
    raise SystemExit('route1as accepted route1ar geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1as frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1as note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
