#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1as-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1at-j8-gnd.py \
  --route1as-drc-json /tmp/route1as.json \
  --route1as-pin-net-audit /tmp/route1as-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1at.json \
  hardware/main-board/pcb/route-r13-1at/AegisBioWatch-MainBoard-Route1at-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1at/AegisBioWatch-MainBoard-Route1at-r13.kicad_pcb \
  --output /tmp/route1at-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1at.json'))
a=json.load(open('/tmp/route1at-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1at/routing-seed-r13-1at.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1at/AegisBioWatch-MainBoard-Route1at-r13.kicad_pcb')
conn=r.get('connections',{}).get('J8.5/GND',{})

accepted_source_sha='c45a7ffc68b505653ec0c87e3c39c0a62f1aa95a2e708891ec16ba6d0ecba429'
accepted_pcb_sha='72dc9a0e2222a1c9a8eb5fa5d27fb4f8533fa14eebfc60c77f40bc1106e787c9'
accepted_artifact_digest='sha256:e7ffd170ceefea42686edfd92f8a4e1e8936516ef936c1dc27b3a701554d60b7'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1as_sha256':r.get('source_route1as_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1as_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'j8_value':conn.get('j8_value'),
  'j8_1_net':conn.get('j8_1_net'),
  'j8_2_net':conn.get('j8_2_net'),
  'j8_3_net':conn.get('j8_3_net'),
  'j8_4_net':conn.get('j8_4_net'),
  'j8_5_net':conn.get('j8_5_net'),
  'j8_6_net':conn.get('j8_6_net'),
  'j8_5_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1as_geometry_modified':r.get('accepted_route1as_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1as_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1at-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=129:
    raise SystemExit('route1at DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1at audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1at routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1at placement scope gate failed')
expected={
    'j8_value':'TC2030_SWD_6',
    'j8_1_net':'+1V8',
    'j8_2_net':'SWDIO',
    'j8_3_net':'NRF_RESET_N',
    'j8_4_net':'SWDCLK',
    'j8_5_net':'GND',
    'j8_6_net':'SWO',
}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1at J8 identity/net gate failed: {key}={out[key]!r}')
if out['j8_5_pad_mm'] != [14.645,15.26] or out['gnd_via_mm'] != [14.645,16.0]:
    raise SystemExit('route1at J8 geometry gate failed')
if out['accepted_route1as_geometry_modified'] is not False:
    raise SystemExit('route1at accepted route1as geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1at frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1at note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
