#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1av-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1aw-j101-gnd.py \
  --route1av-drc-json /tmp/route1av.json \
  --route1av-pin-net-audit /tmp/route1av-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1aw.json \
  hardware/main-board/pcb/route-r13-1aw/AegisBioWatch-MainBoard-Route1aw-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1aw/AegisBioWatch-MainBoard-Route1aw-r13.kicad_pcb \
  --output /tmp/route1aw-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1aw.json'))
a=json.load(open('/tmp/route1aw-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1aw/routing-seed-r13-1aw.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1aw/AegisBioWatch-MainBoard-Route1aw-r13.kicad_pcb')
conn=r.get('connections',{}).get('J101.2/GND lower',{})

accepted_source_sha='0d3f6acb60080c72a92c3d9d0075a375c7e6fc1ac2b4bfdd6357552b0e484113'
accepted_pcb_sha='646c8daedef7c835c859c320999523e7a9ddf07ade6864d1e6e194cf9665d422'
accepted_artifact_digest='sha256:6e9ff50534c0dba9d18bcaec2854e1145163c18cacbba55837234798644c6dc3'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1av_sha256':r.get('source_route1av_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1av_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'j101_value':conn.get('j101_value'),
  'j101_1_net':conn.get('j101_1_net'),
  'j101_2_net':conn.get('j101_2_net'),
  'j101_1_pads_mm':conn.get('j101_1_pads_mm'),
  'j101_2_pads_mm':conn.get('j101_2_pads_mm'),
  'target_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1av_geometry_modified':r.get('accepted_route1av_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1av_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1aw-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=126:
    raise SystemExit('route1aw DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1aw audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1aw routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1aw placement scope gate failed')
expected={'j101_value':'EVQPLDA15_SHIP_WAKE','j101_1_net':'SHIP_HOLD','j101_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1aw J101 identity/net gate failed: {key}={out[key]!r}')
if out['j101_1_pads_mm'] != [[34.775,10.625],[34.775,15.025]]:
    raise SystemExit('route1aw J101.1 geometry gate failed')
if out['j101_2_pads_mm'] != [[38.475,10.625],[38.475,15.025]]:
    raise SystemExit('route1aw J101.2 geometry gate failed')
if out['target_pad_mm'] != [38.475,15.025] or out['gnd_via_mm'] != [39.2,15.025]:
    raise SystemExit('route1aw target geometry gate failed')
if out['accepted_route1av_geometry_modified'] is not False:
    raise SystemExit('route1aw accepted route1av geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1aw frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1aw note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
