#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1at-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1au-d102-gnd.py \
  --route1at-drc-json /tmp/route1at.json \
  --route1at-pin-net-audit /tmp/route1at-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1au.json \
  hardware/main-board/pcb/route-r13-1au/AegisBioWatch-MainBoard-Route1au-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1au/AegisBioWatch-MainBoard-Route1au-r13.kicad_pcb \
  --output /tmp/route1au-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1au.json'))
a=json.load(open('/tmp/route1au-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1au/routing-seed-r13-1au.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1au/AegisBioWatch-MainBoard-Route1au-r13.kicad_pcb')
conn=r.get('connections',{}).get('D102.2/GND',{})

accepted_source_sha='59c92f0a8f2d646235c774c24a7a63df97c92b2605ff7a63f1930be4f9ff983f'
accepted_pcb_sha='68cee3dd159ac4f5119cebdff893ba3372435e5a5791cb343c49bfba53c9d975'
accepted_artifact_digest='sha256:ae9f872d355f85727ca31fa09449650bae3484aed0674b5e465f96c199eabd22'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1at_sha256':r.get('source_route1at_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1at_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'd102_value':conn.get('d102_value'),
  'd102_1_net':conn.get('d102_1_net'),
  'd102_2_net':conn.get('d102_2_net'),
  'd102_1_pad_mm':conn.get('d102_1_pad_mm'),
  'd102_2_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1at_geometry_modified':r.get('accepted_route1at_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1at_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1au-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=128:
    raise SystemExit('route1au DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1au audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1au routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1au placement scope gate failed')
expected={'d102_value':'PESD5V0S1UL','d102_1_net':'DOCK_5V_RAW','d102_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1au D102 identity/net gate failed: {key}={out[key]!r}')
if out['d102_1_pad_mm'] != [41.12,10.27] or out['d102_2_pad_mm'] != [41.82,10.27] or out['gnd_via_mm'] != [42.25,10.27]:
    raise SystemExit('route1au D102 geometry gate failed')
if out['accepted_route1at_geometry_modified'] is not False:
    raise SystemExit('route1au accepted route1at geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1au frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1au note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
