#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1bc-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1bd-c3-c4-1v8.py   --route1bc-drc-json /tmp/route1bc.json   --route1bc-pin-net-audit /tmp/route1bc-audit.json

kicad-cli pcb drc --format json --severity-all   -o /tmp/route1bd.json   hardware/main-board/pcb/route-r13-1bd/AegisBioWatch-MainBoard-Route1bd-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py   --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml   --pcb hardware/main-board/pcb/route-r13-1bd/AegisBioWatch-MainBoard-Route1bd-r13.kicad_pcb   --output /tmp/route1bd-audit.json

python3 - <<'PY'
import hashlib,json
from pathlib import Path

d=json.load(open('/tmp/route1bd.json'))
a=json.load(open('/tmp/route1bd-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1bd/routing-seed-r13-1bd.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1bd/AegisBioWatch-MainBoard-Route1bd-r13.kicad_pcb')
c=r.get('connections',{}).get('C3.1/+1V8 to C4.1/+1V8',{})

accepted_pcb_sha='597d86745b63580962a57ee3b04677185648229fd4a5fee1301036cc89fa1690'
accepted_artifact_digest='sha256:9d7dca83481394b87fe6292b444ca04638a54f26ad512f5289151c2ce4c356b7'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'track_width_mm':r.get('track_width_mm'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'c3_value':c.get('c3_value'),'c4_value':c.get('c4_value'),
  'c3_pad1_mm':c.get('c3_pad1_mm'),'c4_pad1_mm':c.get('c4_pad1_mm'),
  'c3_pad1_net':c.get('c3_pad1_net'),'c4_pad1_net':c.get('c4_pad1_net'),
  'c3_pad2_mm':c.get('c3_pad2_mm'),'c4_pad2_mm':c.get('c4_pad2_mm'),
  'c3_pad2_net':c.get('c3_pad2_net'),'c4_pad2_net':c.get('c4_pad2_net'),
  'accepted_route1bc_geometry_modified':r.get('accepted_route1bc_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched')}
out['byte_identity_matches_accepted_artifact']=(out['pcb_sha256']==accepted_pcb_sha)
print(json.dumps(out,indent=2))
Path('/tmp/route1bd-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=119:
    raise SystemExit('route1bd DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1bd audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=0 or out['track_width_mm']!=0.30:
    raise SystemExit('route1bd routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1bd placement scope gate failed')
if out['c3_value']!='100nF' or out['c4_value']!='100nF':
    raise SystemExit('route1bd C3/C4 value gate failed')
if out['c3_pad1_mm']!=[41.005,13.475] or out['c4_pad1_mm']!=[41.005,14.975]:
    raise SystemExit('route1bd target coordinate gate failed')
if out['c3_pad1_net']!='+1V8' or out['c4_pad1_net']!='+1V8':
    raise SystemExit('route1bd target net gate failed')
if out['c3_pad2_mm']!=[41.645,13.475] or out['c4_pad2_mm']!=[41.645,14.975]:
    raise SystemExit('route1bd adjacent GND coordinate gate failed')
if out['c3_pad2_net']!='GND' or out['c4_pad2_net']!='GND':
    raise SystemExit('route1bd adjacent GND net gate failed')
if out['accepted_route1bc_geometry_modified'] is not False:
    raise SystemExit('route1bd accepted route1bc geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1bd frozen-interface scope gate failed')

if not out['byte_identity_matches_accepted_artifact']:
    print('route1bd note: regenerated bytes differ from accepted Artifact provenance; electrical/geometry gates remain authoritative')
PY
