#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1ay-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1az-r304-gnd.py \
  --route1ay-drc-json /tmp/route1ay.json \
  --route1ay-pin-net-audit /tmp/route1ay-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1az.json \
  hardware/main-board/pcb/route-r13-1az/AegisBioWatch-MainBoard-Route1az-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1az/AegisBioWatch-MainBoard-Route1az-r13.kicad_pcb \
  --output /tmp/route1az-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1az.json'))
a=json.load(open('/tmp/route1az-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1az/routing-seed-r13-1az.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1az/AegisBioWatch-MainBoard-Route1az-r13.kicad_pcb')
conn=r.get('connections',{}).get('R304.2/GND',{})

accepted_source_sha='cbb4b10276214cff7063349801b9371dd28a1e82e0227d6a7950ed9abd54e2ba'
accepted_pcb_sha='29a90df3ff7ef6fd038a68bf3bc3e91ae6c9ce6c79ed742eb57b1dcf7b400a4f'
accepted_artifact_digest='sha256:7e4f7091235fadcece258811a9658bdb1ded3d557e7beac00eaaa6d8c81021ec'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1ay_sha256':r.get('source_route1ay_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1ay_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'r304_value':conn.get('r304_value'),
  'r304_1_net':conn.get('r304_1_net'),
  'r304_2_net':conn.get('r304_2_net'),
  'r304_1_pad_mm':conn.get('r304_1_pad_mm'),
  'r304_2_pad_mm':conn.get('r304_2_pad_mm'),
  'target_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1ay_geometry_modified':r.get('accepted_route1ay_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1ay_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1az-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=123:
    raise SystemExit('route1az DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1az audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1az routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1az placement scope gate failed')
expected={'r304_value':'100k PD','r304_1_net':'HAPTIC_EN','r304_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1az R304 identity/net gate failed: {key}={out[key]!r}')
if out['r304_1_pad_mm'] != [24.755,25.975] or out['r304_2_pad_mm'] != [25.395,25.975]:
    raise SystemExit('route1az R304 geometry gate failed')
if out['target_pad_mm'] != [25.395,25.975] or out['gnd_via_mm'] != [25.395,26.63]:
    raise SystemExit('route1az target geometry gate failed')
if out['accepted_route1ay_geometry_modified'] is not False:
    raise SystemExit('route1az accepted route1ay geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1az frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1az note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
