#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1aq-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1ar-c3-gnd.py \
  --route1aq-drc-json /tmp/route1aq.json \
  --route1aq-pin-net-audit /tmp/route1aq-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1ar.json \
  hardware/main-board/pcb/route-r13-1ar/AegisBioWatch-MainBoard-Route1ar-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1ar/AegisBioWatch-MainBoard-Route1ar-r13.kicad_pcb \
  --output /tmp/route1ar-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1ar.json'))
a=json.load(open('/tmp/route1ar-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1ar/routing-seed-r13-1ar.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1ar/AegisBioWatch-MainBoard-Route1ar-r13.kicad_pcb')
conn=r.get('connections',{}).get('C3.2/GND',{})

accepted_source_sha='9924140a48d5e6829a67817e8dfe9c485e80add405adb61e159ac2d22b15f64c'
accepted_pcb_sha='627ff6fc28b916391051058e5719c593b133a1287cff5df2d4056fb0351122cd'
accepted_artifact_digest='sha256:ed9d3466309292ccc3da29ae51cbeff2962e7cad54aba8a6518d6a3e2b2cf3a8'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1aq_sha256':r.get('source_route1aq_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1aq_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'c3_value':conn.get('c3_value'),
  'c3_1_net':conn.get('c3_1_net'),
  'c3_2_net':conn.get('c3_2_net'),
  'c3_2_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1aq_geometry_modified':r.get('accepted_route1aq_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1aq_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1ar-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=131:
    raise SystemExit('route1ar DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1ar audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1ar routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1ar placement scope gate failed')
expected={'c3_value':'100nF','c3_1_net':'+1V8','c3_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1ar C3 identity/net gate failed: {key}={out[key]!r}')
if out['c3_2_pad_mm'] != [41.645,13.475] or out['gnd_via_mm'] != [42.25,13.475]:
    raise SystemExit('route1ar C3 geometry gate failed')
if out['accepted_route1aq_geometry_modified'] is not False:
    raise SystemExit('route1ar accepted route1aq geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1ar frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1ar note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
