#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1am-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1an-j2-gnd.py \
  --route1am-drc-json /tmp/route1am.json \
  --route1am-pin-net-audit /tmp/route1am-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1an.json \
  hardware/main-board/pcb/route-r13-1an/AegisBioWatch-MainBoard-Route1an-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1an/AegisBioWatch-MainBoard-Route1an-r13.kicad_pcb \
  --output /tmp/route1an-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1an.json'))
a=json.load(open('/tmp/route1an-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1an/routing-seed-r13-1an.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1an/AegisBioWatch-MainBoard-Route1an-r13.kicad_pcb')
conn=r.get('connections',{}).get('J2.3/GND',{})

accepted_source_sha='c202f52e0b596acf806dbc38981cec932ebe845faca9e831506fc7cb99dd5e86'
accepted_pcb_sha='8600d5079e560b335835719bae895bae9248293528977a1eac0cf5747bc687e6'
accepted_artifact_digest='sha256:425159441fec309916406449dac0f738504145317612344343577368f46a16c6'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1am_sha256':r.get('source_route1am_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1am_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'j2_value':conn.get('j2_value'),
  'j2_1_net':conn.get('j2_1_net'),
  'j2_2_net':conn.get('j2_2_net'),
  'j2_3_net':'GND' if 'J2.3/GND' in r.get('connections',{}) else None,
  'j2_3_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1am_geometry_modified':r.get('accepted_route1am_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1am_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1an-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=135:
    raise SystemExit('route1an DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1an audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1an routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1an placement scope gate failed')
if out['j2_value']!='BATTERY_PACK_300mAh_3WIRE' or out['j2_1_net']!='VBAT' or out['j2_2_net']!='BAT_NTC' or out['j2_3_net']!='GND':
    raise SystemExit('route1an J2 identity/net gate failed')
if out['j2_3_pad_mm'] != [7.025,11.7725] or out['gnd_via_mm'] != [7.025,11.0225]:
    raise SystemExit('route1an J2 geometry gate failed')
if out['accepted_route1am_geometry_modified'] is not False:
    raise SystemExit('route1an accepted route1am geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1an frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
# A pull_request run can regenerate different bytes as its synthesized merge
# base evolves; topology/geometry/DRC/audit/component-identity gates remain
# authoritative.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1an note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
