#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1ap-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1aq-c2-gnd.py \
  --route1ap-drc-json /tmp/route1ap.json \
  --route1ap-pin-net-audit /tmp/route1ap-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1aq.json \
  hardware/main-board/pcb/route-r13-1aq/AegisBioWatch-MainBoard-Route1aq-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1aq/AegisBioWatch-MainBoard-Route1aq-r13.kicad_pcb \
  --output /tmp/route1aq-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1aq.json'))
a=json.load(open('/tmp/route1aq-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1aq/routing-seed-r13-1aq.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1aq/AegisBioWatch-MainBoard-Route1aq-r13.kicad_pcb')
conn=r.get('connections',{}).get('C2.2/GND',{})

accepted_source_sha='fbd83553f4af789f4f9ec51ba576577d700fdff341eeb27aee4c8aa35cb69045'
accepted_pcb_sha='6e9517356c6168ff1f20b3265c9f85a183cdb9e997581b0de2b26100ec3b3c27'
accepted_artifact_digest='sha256:c0d24481ff98a11466a139d3d2d2357e9c0a7888de48c57d3070bc693209052a'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1ap_sha256':r.get('source_route1ap_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1ap_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'c2_value':conn.get('c2_value'),
  'c2_1_net':conn.get('c2_1_net'),
  'c2_2_net':conn.get('c2_2_net'),
  'c2_2_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1ap_geometry_modified':r.get('accepted_route1ap_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1ap_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1aq-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=132:
    raise SystemExit('route1aq DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1aq audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1aq routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1aq placement scope gate failed')
expected={'c2_value':'100nF','c2_1_net':'+1V8','c2_2_net':'GND'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1aq C2 identity/net gate failed: {key}={out[key]!r}')
if out['c2_2_pad_mm'] != [41.645,11.975] or out['gnd_via_mm'] != [42.25,11.975]:
    raise SystemExit('route1aq C2 geometry gate failed')
if out['accepted_route1ap_geometry_modified'] is not False:
    raise SystemExit('route1aq accepted route1ap geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1aq frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1aq note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
