#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1au-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1av-u4-gnd.py \
  --route1au-drc-json /tmp/route1au.json \
  --route1au-pin-net-audit /tmp/route1au-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1av.json \
  hardware/main-board/pcb/route-r13-1av/AegisBioWatch-MainBoard-Route1av-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1av/AegisBioWatch-MainBoard-Route1av-r13.kicad_pcb \
  --output /tmp/route1av-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1av.json'))
a=json.load(open('/tmp/route1av-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1av/routing-seed-r13-1av.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1av/AegisBioWatch-MainBoard-Route1av-r13.kicad_pcb')
conn=r.get('connections',{}).get('U4.8/GND',{})

accepted_source_sha='386280d37e48927199c34f34bbfa02476dd9f5eaf30825e6f0bb8c1636d37a82'
accepted_pcb_sha='0eb45a682b54c23e393f6471a418f679d9b2f2cb22e5b6cada464a00eb03d249'
accepted_artifact_digest='sha256:01a76f90dea5bc9111534de894e4943d7de584e017dcd644f9f83a4d11a1656c'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1au_sha256':r.get('source_route1au_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1au_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'u4_value':conn.get('u4_value'),
  'u4_7_net':conn.get('u4_7_net'),
  'u4_8_net':conn.get('u4_8_net'),
  'u4_9_net':conn.get('u4_9_net'),
  'u4_7_pad_mm':conn.get('u4_7_pad_mm'),
  'u4_8_pad_mm':conn.get('pad_mm'),
  'u4_9_pad_mm':conn.get('u4_9_pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1au_geometry_modified':r.get('accepted_route1au_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1au_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1av-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=127:
    raise SystemExit('route1av DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1av audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1av routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1av placement scope gate failed')
expected={'u4_value':'DRV2605LDGSR','u4_7_net':'HAPTIC_OUT_P','u4_8_net':'GND','u4_9_net':'HAPTIC_OUT_N'}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1av U4 identity/net gate failed: {key}={out[key]!r}')
if out['u4_7_pad_mm'] != [23.005,14.9] or out['u4_8_pad_mm'] != [23.005,14.4] or out['u4_9_pad_mm'] != [23.005,13.9] or out['gnd_via_mm'] != [24.1,14.4]:
    raise SystemExit('route1av U4 geometry gate failed')
if out['accepted_route1au_geometry_modified'] is not False:
    raise SystemExit('route1av accepted route1au geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1av frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1av note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
