#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1ao-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1ap-c13-gnd.py \
  --route1ao-drc-json /tmp/route1ao.json \
  --route1ao-pin-net-audit /tmp/route1ao-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1ap.json \
  hardware/main-board/pcb/route-r13-1ap/AegisBioWatch-MainBoard-Route1ap-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1ap/AegisBioWatch-MainBoard-Route1ap-r13.kicad_pcb \
  --output /tmp/route1ap-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1ap.json'))
a=json.load(open('/tmp/route1ap-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1ap/routing-seed-r13-1ap.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1ap/AegisBioWatch-MainBoard-Route1ap-r13.kicad_pcb')
conn=r.get('connections',{}).get('C13.2/GND',{})

accepted_source_sha='a3c912efbbba1234dc3df2ac06b3fb62341f4bd96a33d069a816443bf188d457'
accepted_pcb_sha='21c7ed167c78f44e0039e0e2ab0eb02709c03fd3b928b431241d69aea49ab7dc'
accepted_artifact_digest='sha256:efaead8852b50dff59d4c2577b6e388c309905f856b7df6dae8878fcacc669b7'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1ao_sha256':r.get('source_route1ao_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1ao_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'c13_value':conn.get('c13_value'),
  'c13_1_net':conn.get('c13_1_net'),
  'c13_2_net':conn.get('c13_2_net'),
  'c13_2_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'accepted_route1ao_geometry_modified':r.get('accepted_route1ao_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1ao_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1ap-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=133:
    raise SystemExit('route1ap DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1ap audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1ap routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1ap placement scope gate failed')
expected={
  'c13_value':'3.9pF',
  'c13_1_net':'NRF_RESET_RAW',
  'c13_2_net':'GND',
}
for key,value in expected.items():
    if out[key]!=value:
        raise SystemExit(f'route1ap C13 identity/net gate failed: {key}={out[key]!r}')
if out['c13_2_pad_mm'] != [40.895,22.975] or out['gnd_via_mm'] != [41.55,22.975]:
    raise SystemExit('route1ap C13 geometry gate failed')
if out['accepted_route1ao_geometry_modified'] is not False:
    raise SystemExit('route1ap accepted route1ao geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1ap frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
# A pull_request run can regenerate different bytes as its synthesized merge
# base evolves; topology/geometry/DRC/audit/component-identity gates remain
# authoritative.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1ap note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
