#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1az-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1ba-j9-gnd.py \
  --route1az-drc-json /tmp/route1az.json \
  --route1az-pin-net-audit /tmp/route1az-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1ba.json \
  hardware/main-board/pcb/route-r13-1ba/AegisBioWatch-MainBoard-Route1ba-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1ba/AegisBioWatch-MainBoard-Route1ba-r13.kicad_pcb \
  --output /tmp/route1ba-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1ba.json'))
a=json.load(open('/tmp/route1ba-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1ba/routing-seed-r13-1ba.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1ba/AegisBioWatch-MainBoard-Route1ba-r13.kicad_pcb')
conn=r.get('connections',{}).get('J9.1/GND right pad',{})

accepted_source_sha='9c6e2447b20bc6828108adf049ec767ffafaeac80cd837794963a38608d8444f'
accepted_pcb_sha='83a8d08f0eb816ef1450aa7305eb97d09d2ac669dfb8eb6211b0f3dc20dfb64f'
accepted_artifact_digest='sha256:0836fcb3d9e86b14c869e3e74e6bf0e52cb263e5ad8f128524acb9264886443a'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1az_sha256':r.get('source_route1az_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1az_sha256':accepted_source_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'j9_value':conn.get('j9_value'),
  'j9_1_net':conn.get('j9_1_net'),
  'j9_2_net':conn.get('j9_2_net'),
  'j9_1_pad_positions_mm':conn.get('j9_1_pad_positions_mm'),
  'j9_2_pad_positions_mm':conn.get('j9_2_pad_positions_mm'),
  'target_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
  'target_physical_pad':conn.get('target_physical_pad'),
  'left_j9_1_gnd_pad_status':r.get('left_j9_1_gnd_pad_status'),
  'j9_side_button_pads_status':r.get('j9_side_button_pads_status'),
  'accepted_route1az_geometry_modified':r.get('accepted_route1az_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1az_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1ba-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=122:
    raise SystemExit('route1ba DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1ba audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1ba routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1ba placement scope gate failed')
if out['j9_value']!='EVQPUK02K_SIDE_BUTTON' or out['j9_1_net']!='GND' or out['j9_2_net']!='SIDE_BUTTON':
    raise SystemExit('route1ba J9 identity/net gate failed')
if out['j9_1_pad_positions_mm'] != [[20.85,5.775],[26.0,5.775]]:
    raise SystemExit('route1ba J9.1 duplicate-pad geometry gate failed')
if out['j9_2_pad_positions_mm'] != [[20.85,7.475],[26.0,7.475]]:
    raise SystemExit('route1ba J9.2 geometry gate failed')
if out['target_pad_mm'] != [26.0,5.775] or out['gnd_via_mm'] != [27.0,5.775] or out['target_physical_pad']!='right J9.1/GND':
    raise SystemExit('route1ba target geometry gate failed')
if out['left_j9_1_gnd_pad_status']!='UNCHANGED' or out['j9_side_button_pads_status']!='UNCHANGED':
    raise SystemExit('route1ba J9 preserved-pad gate failed')
if out['accepted_route1az_geometry_modified'] is not False:
    raise SystemExit('route1ba accepted route1az geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1ba frozen-interface scope gate failed')

# Accepted Artifact hashes are provenance records, not electrical gates.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1ba note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
