#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1bb-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1bc-c2-c3-1v8.py   --route1bb-drc-json /tmp/route1bb.json   --route1bb-pin-net-audit /tmp/route1bb-audit.json

kicad-cli pcb drc --format json --severity-all   -o /tmp/route1bc.json   hardware/main-board/pcb/route-r13-1bc/AegisBioWatch-MainBoard-Route1bc-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py   --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml   --pcb hardware/main-board/pcb/route-r13-1bc/AegisBioWatch-MainBoard-Route1bc-r13.kicad_pcb   --output /tmp/route1bc-audit.json

python3 - <<'PY'
import hashlib,json
from pathlib import Path

d=json.load(open('/tmp/route1bc.json'))
a=json.load(open('/tmp/route1bc-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1bc/routing-seed-r13-1bc.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1bc/AegisBioWatch-MainBoard-Route1bc-r13.kicad_pcb')
c=r.get('connections',{}).get('C2.1/+1V8 to C3.1/+1V8',{})

accepted_pcb_sha='d87852ebdefd0d260848738084fabd54cec9f487d77672c01b06a550eaf214f6'
accepted_artifact_digest='sha256:affba96dbf26ba582e2d596abe5b724c4205fb0ac254b2f67c1017acc418de4d'

out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'track_width_mm':r.get('track_width_mm'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'accepted_artifact_digest':accepted_artifact_digest,
  'byte_identity_matches_accepted_artifact':False,
  'c2_value':c.get('c2_value'),'c3_value':c.get('c3_value'),
  'c2_pad1_mm':c.get('c2_pad1_mm'),'c3_pad1_mm':c.get('c3_pad1_mm'),
  'c2_pad1_net':c.get('c2_pad1_net'),'c3_pad1_net':c.get('c3_pad1_net'),
  'c2_pad2_mm':c.get('c2_pad2_mm'),'c3_pad2_mm':c.get('c3_pad2_mm'),
  'c2_pad2_net':c.get('c2_pad2_net'),'c3_pad2_net':c.get('c3_pad2_net'),
  'accepted_route1bb_geometry_modified':r.get('accepted_route1bb_geometry_modified'),
  'rf_routing_touched':r.get('rf_routing_touched'),
  'supplier_gated_interfaces_touched':r.get('supplier_gated_interfaces_touched')}
out['byte_identity_matches_accepted_artifact']=(out['pcb_sha256']==accepted_pcb_sha)
print(json.dumps(out,indent=2))
Path('/tmp/route1bc-summary.json').write_text(json.dumps(out,indent=2))

if out['rule_violations']!=0 or out['unconnected_items']!=120:
    raise SystemExit('route1bc DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1bc audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=0 or out['track_width_mm']!=0.30:
    raise SystemExit('route1bc routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1bc placement scope gate failed')
if out['c2_value']!='100nF' or out['c3_value']!='100nF':
    raise SystemExit('route1bc C2/C3 value gate failed')
if out['c2_pad1_mm']!=[41.005,11.975] or out['c3_pad1_mm']!=[41.005,13.475]:
    raise SystemExit('route1bc target coordinate gate failed')
if out['c2_pad1_net']!='+1V8' or out['c3_pad1_net']!='+1V8':
    raise SystemExit('route1bc target net gate failed')
if out['c2_pad2_mm']!=[41.645,11.975] or out['c3_pad2_mm']!=[41.645,13.475]:
    raise SystemExit('route1bc adjacent GND coordinate gate failed')
if out['c2_pad2_net']!='GND' or out['c3_pad2_net']!='GND':
    raise SystemExit('route1bc adjacent GND net gate failed')
if out['accepted_route1bb_geometry_modified'] is not False:
    raise SystemExit('route1bc accepted route1bb geometry mutation gate failed')
if out['rf_routing_touched'] is not False or out['supplier_gated_interfaces_touched'] is not False:
    raise SystemExit('route1bc frozen-interface scope gate failed')

if not out['byte_identity_matches_accepted_artifact']:
    print('route1bc note: regenerated bytes differ from accepted Artifact provenance; electrical/geometry gates remain authoritative')
PY
