#!/usr/bin/env bash
set -euo pipefail

bash tools/reproduce-route1ak-accepted.sh

python3 -X faulthandler tools/materialize-pcb-r13-route1al-c5-gnd.py \
  --route1ak-drc-json /tmp/route1ak.json \
  --route1ak-pin-net-audit /tmp/route1ak-audit.json

kicad-cli pcb drc --format json --severity-all \
  -o /tmp/route1al.json \
  hardware/main-board/pcb/route-r13-1al/AegisBioWatch-MainBoard-Route1al-r13.kicad_pcb

python3 tools/audit-pcb-pin-nets.py \
  --xml hardware/main-board/kicad/recovered-r8/AegisBioWatch-MainBoard-r8-recovered.xml \
  --pcb hardware/main-board/pcb/route-r13-1al/AegisBioWatch-MainBoard-Route1al-r13.kicad_pcb \
  --output /tmp/route1al-audit.json

python3 - <<'PY'
import hashlib
import json
from pathlib import Path

d=json.load(open('/tmp/route1al.json'))
a=json.load(open('/tmp/route1al-audit.json'))
r=json.load(open('hardware/main-board/pcb/route-r13-1al/routing-seed-r13-1al.json'))
pcb=Path('hardware/main-board/pcb/route-r13-1al/AegisBioWatch-MainBoard-Route1al-r13.kicad_pcb')
accepted_source_sha='53f3749600b64e8e95acf18f98e63cf1e4ece2c3939bd6add48f061fcedf1699'
historical_route1ak_sha='254c5861aef41cb0b083779183dbb089e4ce807b1015df2d033a3e64ba265601'
accepted_pcb_sha='6d405a7c0aedd048bd81c8479d1d7cabe6c90514fff6fc95c6c6a2d93b016590'
conn=r.get('connections',{}).get('C5.2/GND',{})
out={
  'rule_violations':len(d.get('violations',[])),
  'unconnected_items':len(d.get('unconnected_items',[])),
  'pin_net_audit':a.get('result'),
  'audited_nodes':a.get('audited_present_source_nodes'),
  'added_segments':r.get('track_segments_added'),
  'vias_added':r.get('vias_added'),
  'component_moves':r.get('component_moves'),
  'component_rotations':r.get('component_rotations'),
  'source_route1ak_sha256':r.get('source_route1ak_sha256'),
  'pcb_sha256':hashlib.sha256(pcb.read_bytes()).hexdigest(),
  'accepted_artifact_source_route1ak_sha256':accepted_source_sha,
  'historical_accepted_route1ak_artifact_sha256':historical_route1ak_sha,
  'accepted_artifact_pcb_sha256':accepted_pcb_sha,
  'byte_identity_matches_accepted_artifact':False,
  'c5_value':conn.get('c5_value'),
  'c5_1_net':conn.get('c5_1_net'),
  'c5_2_net':'GND' if 'C5.2/GND' in r.get('connections',{}) else None,
  'c5_2_pad_mm':conn.get('pad_mm'),
  'gnd_via_mm':conn.get('gnd_via_mm'),
}
out['byte_identity_matches_accepted_artifact']=(
    out['source_route1ak_sha256']==accepted_source_sha and
    out['pcb_sha256']==accepted_pcb_sha
)
print(json.dumps(out,indent=2))
Path('/tmp/route1al-summary.json').write_text(json.dumps(out,indent=2))
if out['rule_violations']!=0 or out['unconnected_items']!=137:
    raise SystemExit('route1al DRC/ratsnest gate failed')
if out['pin_net_audit']!='PASS' or out['audited_nodes']!=268:
    raise SystemExit('route1al audit gate failed')
if out['added_segments']!=1 or out['vias_added']!=1:
    raise SystemExit('route1al routing scope gate failed')
if out['component_moves']!=[] or out['component_rotations']!=[]:
    raise SystemExit('route1al placement scope gate failed')
if out['c5_value']!='100nF' or out['c5_1_net']!='+1V8' or out['c5_2_net']!='GND':
    raise SystemExit('route1al C5 identity/net gate failed')
if out['c5_2_pad_mm'] != [9.895,22.225] or out['gnd_via_mm'] != [10.55,22.225]:
    raise SystemExit('route1al C5 geometry gate failed')
# Accepted artifact byte hashes are provenance records, not electrical gates.
# pull_request runs can regenerate different bytes as their synthesized merge
# base evolves; topology/geometry/DRC/audit/identity gates remain authoritative.
if not out['byte_identity_matches_accepted_artifact']:
    print('route1al note: regenerated bytes differ from accepted artifact provenance; electrical/geometry gates remain authoritative')
PY
